"""empty message

Revision ID: 303ab28adc89
Revises: 8184eada3bf4
Create Date: 2019-08-25 18:02:31.584003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '303ab28adc89'
down_revision = '8184eada3bf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('role', 'desription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('desription', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('role', 'description')
    # ### end Alembic commands ###
